#!/usr/bin/env bash
#
# sync-deploy.sh — regenerate the committed deploy config from a single source.
#
# The reserve contract addresses live in ONE place: the operator deploy env that
# bootstrap.sh writes (repo-root .env.local by default). This script reads those
# addresses, resolves each deposit asset's code + issuer ON-CHAIN (from the SAC's
# `name()`), and regenerates the two committed copies so they can never drift:
#
#   - frontend/.env.example          (the NEXT_PUBLIC_* the frontend reads)
#   - docs/reference/deployments.md  (the docs reference table)
#
# Resolving codes/issuers from the chain — not from the deploy env — is the part
# that catches a stale/wrong issuer (the class of bug this guards against).
#
# Usage:
#   make sync-deploy                       # uses ./.env.local
#   scripts/sync-deploy.sh path/to/deploy.env
#
# Env overrides: STELLAR_SOURCE (default `default`), STELLAR_NETWORK (`testnet`),
# RPC_URL, NETWORK_PASSPHRASE, EXPLORER_BASE, TESOURO_PRICE_BRL.
#
# Portable to macOS Bash 3.2 (no associative arrays).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_ENV="${1:-$ROOT/.env.local}"
SRC="${STELLAR_SOURCE:-default}"
NET="${STELLAR_NETWORK:-testnet}"
RPC_URL="${RPC_URL:-https://soroban-testnet.stellar.org}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"
EXPLORER_BASE="${EXPLORER_BASE:-https://stellar.expert/explorer/testnet}"
TESOURO_PRICE_BRL="${TESOURO_PRICE_BRL:-1.22107}"

[ -f "$DEPLOY_ENV" ] || { echo "✗ deploy env not found: $DEPLOY_ENV" >&2; exit 1; }
command -v stellar >/dev/null || { echo "✗ stellar CLI required (brew install stellar-cli)" >&2; exit 1; }

# Read a KEY=value (public address) from the deploy env; ignores secrets/comments.
get() { grep -E "^$1=" "$DEPLOY_ENV" | head -1 | cut -d= -f2- | tr -d '"' | xargs; }

# Resolve a SAC's "CODE:ISSUER" via its on-chain name(). The chain is the source
# of truth for the asset behind the vault — never the deploy env's issuer field.
sac_name() { stellar contract invoke --network "$NET" --source-account "$SRC" --id "$1" -- name 2>/dev/null | tr -d '"'; }

require() { [ -n "$2" ] || { echo "✗ missing $1 in $DEPLOY_ENV" >&2; exit 1; }; }

# ── Reserve addresses (the single source: the deploy env) ─────────────────────
MUSD_VAULT=$(get MUSD_VAULT);       MUSD_POLICY=$(get MUSD_POLICY)
MUSD_REGISTRY=$(get MUSD_REGISTRY); MUSD_SAC=$(get MUSD_SAC); MUSD_FAUCET=$(get MUSD_FAUCET)
MTESOURO_VAULT=$(get MTESOURO_VAULT);       MTESOURO_POLICY=$(get MTESOURO_POLICY)
MTESOURO_REGISTRY=$(get MTESOURO_REGISTRY); MTESOURO_SAC=$(get MTESOURO_SAC); MTESOURO_FAUCET=$(get MTESOURO_FAUCET)
MBRL_VAULT=$(get MBRL_VAULT);       MBRL_POLICY=$(get MBRL_POLICY)
MBRL_REGISTRY=$(get MBRL_REGISTRY); MBRL_SAC=$(get MBRL_SAC); MBRL_FAUCET=$(get MBRL_FAUCET)

for v in MUSD_VAULT MUSD_POLICY MUSD_REGISTRY MUSD_SAC MUSD_FAUCET \
         MTESOURO_VAULT MTESOURO_POLICY MTESOURO_REGISTRY MTESOURO_SAC MTESOURO_FAUCET \
         MBRL_VAULT MBRL_POLICY MBRL_REGISTRY MBRL_SAC MBRL_FAUCET; do
  require "$v" "$(eval echo \"\$$v\")"
done

# ── Asset code + issuer, resolved on-chain from each SAC ──────────────────────
echo "→ resolving asset metadata on-chain ($NET)…"
musd_n="$(sac_name "$MUSD_SAC")";         [ -n "$musd_n" ] || { echo "✗ name() failed for MUSD SAC $MUSD_SAC" >&2; exit 1; }
mtesouro_n="$(sac_name "$MTESOURO_SAC")"; [ -n "$mtesouro_n" ] || { echo "✗ name() failed for MTESOURO SAC $MTESOURO_SAC" >&2; exit 1; }
mbrl_n="$(sac_name "$MBRL_SAC")";         [ -n "$mbrl_n" ] || { echo "✗ name() failed for MBRL SAC $MBRL_SAC" >&2; exit 1; }
MUSD_CODE="${musd_n%%:*}";         MUSD_ISSUER="${musd_n##*:}"
MTESOURO_CODE="${mtesouro_n%%:*}"; MTESOURO_ISSUER="${mtesouro_n##*:}"
MBRL_CODE="${mbrl_n%%:*}";         MBRL_ISSUER="${mbrl_n##*:}"
echo "  MUSD: $MUSD_CODE / $MUSD_ISSUER"
echo "  MTESOURO: $MTESOURO_CODE / $MTESOURO_ISSUER"
echo "  MBRL: $MBRL_CODE / $MBRL_ISSUER"

# ── Generate frontend/.env.example ────────────────────────────────────────────
cat > "$ROOT/frontend/.env.example" <<EOF
# Mutav Pulse — frontend env. Pre-filled with the LIVE testnet deploy, so a fresh
# clone just needs \`cp .env.example .env.local\`. All values are public testnet
# contract/asset IDs (no secrets). Three reserves live: MUSD · MTESOURO · MBRL.
#
# GENERATED by scripts/sync-deploy.sh from the deploy env — do not edit by hand;
# re-run \`make sync-deploy\` after a redeploy.

# ── Stellar network (testnet) ──
NEXT_PUBLIC_RPC_URL=$RPC_URL
NEXT_PUBLIC_NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE
NEXT_PUBLIC_EXPLORER_BASE=$EXPLORER_BASE

# ── MUSD reserve (USD · $MUSD_CODE) — the primary reserve ──
NEXT_PUBLIC_VAULT_ID=$MUSD_VAULT
NEXT_PUBLIC_POLICY_ID=$MUSD_POLICY
NEXT_PUBLIC_REGISTRY_ID=$MUSD_REGISTRY
NEXT_PUBLIC_USDC_ID=$MUSD_SAC
NEXT_PUBLIC_USDC_CODE=$MUSD_CODE
NEXT_PUBLIC_USDC_ISSUER=$MUSD_ISSUER
NEXT_PUBLIC_FAUCET_ID=$MUSD_FAUCET

# ── MTESOURO reserve (Brazilian treasury · $MTESOURO_CODE) ──
NEXT_PUBLIC_MTESOURO_VAULT_ID=$MTESOURO_VAULT
NEXT_PUBLIC_MTESOURO_POLICY_ID=$MTESOURO_POLICY
NEXT_PUBLIC_MTESOURO_REGISTRY_ID=$MTESOURO_REGISTRY
NEXT_PUBLIC_TESOURO_CODE=$MTESOURO_CODE
NEXT_PUBLIC_TESOURO_ISSUER=$MTESOURO_ISSUER
NEXT_PUBLIC_TESOURO_PRICE_BRL=$TESOURO_PRICE_BRL
NEXT_PUBLIC_TESOURO_FAUCET_ID=$MTESOURO_FAUCET

# ── MBRL reserve (BRL-native · $MBRL_CODE) ──
NEXT_PUBLIC_MBRL_VAULT_ID=$MBRL_VAULT
NEXT_PUBLIC_MBRL_POLICY_ID=$MBRL_POLICY
NEXT_PUBLIC_MBRL_REGISTRY_ID=$MBRL_REGISTRY
NEXT_PUBLIC_CBRL_CODE=$MBRL_CODE
NEXT_PUBLIC_CBRL_ISSUER=$MBRL_ISSUER
NEXT_PUBLIC_CBRL_FAUCET_ID=$MBRL_FAUCET
EOF

# ── Generate docs/reference/deployments.md ────────────────────────────────────
row() { # contract-label  address  env-var-cell
  printf '| %s | [`%s`](%s/contract/%s) | %s |\n' "$1" "$2" "$EXPLORER_BASE" "$2" "$3"
}
{
cat <<EOF
# Testnet deployments

Live contract addresses and network configuration for the mutav-pulse reserves on
Stellar testnet. **Three reserves are live** — MUSD, MTESOURO, MBRL. These are
testnet artifacts; a redeploy (\`bootstrap.sh\`) issues new contract IDs. The
frontend reads every address from a \`NEXT_PUBLIC_*\` env var — it never hardcodes
them (see [\`../../frontend/.env.example\`](../../frontend/.env.example)).

> Generated by \`scripts/sync-deploy.sh\` — re-run \`make sync-deploy\` after a redeploy.

## Network

| Field | Value |
|---|---|
| Network | Stellar testnet |
| RPC URL | \`$RPC_URL\` |
| Network passphrase | \`$NETWORK_PASSPHRASE\` |
| Explorer | \`$EXPLORER_BASE\` |

## Reserves

Each reserve is its own contract set (vault + policy + registry), pegged to a
currency and settling in its own deposit token. Click an address to verify on
Stellar Expert.

### MUSD — USD reserve (deposit token: $MUSD_CODE)

| Contract | Address | Env var |
|---|---|---|
$(row vault "$MUSD_VAULT" '`NEXT_PUBLIC_VAULT_ID`')
$(row policy "$MUSD_POLICY" '`NEXT_PUBLIC_POLICY_ID`')
$(row registry "$MUSD_REGISTRY" '`NEXT_PUBLIC_REGISTRY_ID`')
$(row "$MUSD_CODE SAC (underlying)" "$MUSD_SAC" '`NEXT_PUBLIC_USDC_ID`')
$(row faucet "$MUSD_FAUCET" '`NEXT_PUBLIC_FAUCET_ID`')

### MTESOURO — Brazilian-treasury reserve (deposit token: $MTESOURO_CODE)

| Contract | Address | Env var |
|---|---|---|
$(row vault "$MTESOURO_VAULT" '`NEXT_PUBLIC_MTESOURO_VAULT_ID`')
$(row policy "$MTESOURO_POLICY" '`NEXT_PUBLIC_MTESOURO_POLICY_ID`')
$(row registry "$MTESOURO_REGISTRY" '`NEXT_PUBLIC_MTESOURO_REGISTRY_ID`')
$(row "$MTESOURO_CODE SAC (underlying)" "$MTESOURO_SAC" '— (read on-chain)')
$(row faucet "$MTESOURO_FAUCET" '`NEXT_PUBLIC_TESOURO_FAUCET_ID`')

### MBRL — BRL-native reserve (deposit token: $MBRL_CODE)

| Contract | Address | Env var |
|---|---|---|
$(row vault "$MBRL_VAULT" '`NEXT_PUBLIC_MBRL_VAULT_ID`')
$(row policy "$MBRL_POLICY" '`NEXT_PUBLIC_MBRL_POLICY_ID`')
$(row registry "$MBRL_REGISTRY" '`NEXT_PUBLIC_MBRL_REGISTRY_ID`')
$(row "$MBRL_CODE SAC (underlying)" "$MBRL_SAC" '— (read on-chain)')
$(row faucet "$MBRL_FAUCET" '`NEXT_PUBLIC_CBRL_FAUCET_ID`')

## Deposit assets

All three deposit tokens are **mock classic assets** on testnet. Each vault's
\`underlying\` is the asset's Stellar Asset Contract (SAC) above.

| Asset | Code | Issuer |
|---|---|---|
| MUSD deposit | \`$MUSD_CODE\` | \`$MUSD_ISSUER\` |
| MTESOURO deposit | \`$MTESOURO_CODE\` | \`$MTESOURO_ISSUER\` |
| MBRL deposit | \`$MBRL_CODE\` | \`$MBRL_ISSUER\` |

(cTSR is yield-bearing ≈ R\$1.22, not 1:1; cUSD/cBRL are 1:1-pegged.)

## Notes

- All addresses are **testnet-only**; a redeploy via \`bootstrap.sh\` changes every
  contract ID. Re-run \`make sync-deploy\` to regenerate this file + \`.env.example\`.
- The two-leg fiança policy is live: each reserve's \`policy\` exposes \`cover_default\`,
  \`cover_exit\`, \`grace_secs\`, and \`set_coverage_ratio_bps\`.
- For the per-method contract surface, see [\`./contracts/vault.md\`](./contracts/vault.md);
  for revert codes see [\`./errors.md\`](./errors.md).
EOF
} > "$ROOT/docs/reference/deployments.md"

echo "✓ regenerated:"
echo "    frontend/.env.example"
echo "    docs/reference/deployments.md"
echo "  review with: git diff -- frontend/.env.example docs/reference/deployments.md"
