#!/usr/bin/env bash
#
# sync-deploy.sh — regenerate the committed deploy config from one source.
#
# The reserve contract addresses live in ONE place: the operator deploy record
# (repo-root .env.local by default) — a file YOU populate from bootstrap.sh's
# output after each deploy (bootstrap echoes raw IDs; you map them onto the
# MUSD_/MTESOURO_/MBRL_ prefixed keys here). This script reads those addresses,
# VALIDATES each vault on-chain (its underlying must match the configured SAC, so
# a stale id is caught, not laundered), resolves each deposit asset's code +
# issuer from the SAC's on-chain name(), and regenerates the THREE committed
# copies so they can't drift:
#
#   - frontend/.env.example          (the NEXT_PUBLIC_* the frontend reads)
#   - docs/reference/deployments.md  (the docs reference table)
#   - README.md                      (the "Live on testnet" block, between
#                                      <!-- deploy:start --> / <!-- deploy:end -->)
#
# Resolving codes/issuers from the chain — not from the deploy record — is the
# part that catches a stale/wrong issuer (the class of bug this guards against).
#
# Usage:
#   make sync-deploy                       # uses ./.env.local
#   scripts/sync-deploy.sh path/to/deploy.env
#
# Env overrides: STELLAR_SOURCE (default `default`), STELLAR_NETWORK (`testnet`),
# RPC_URL, NETWORK_PASSPHRASE, EXPLORER_BASE, TESOURO_PRICE_BRL.
#
# Portable to macOS Bash 3.2 (no associative arrays).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEPLOY_ENV="${1:-$ROOT/.env.local}"
SRC="${STELLAR_SOURCE:-default}"
NET="${STELLAR_NETWORK:-testnet}"
RPC_URL="${RPC_URL:-https://soroban-testnet.stellar.org}"
NETWORK_PASSPHRASE="${NETWORK_PASSPHRASE:-Test SDF Network ; September 2015}"
EXPLORER_BASE="${EXPLORER_BASE:-https://stellar.expert/explorer/testnet}"
TESOURO_PRICE_BRL="${TESOURO_PRICE_BRL:-1.22107}"

[ -f "$DEPLOY_ENV" ] || { echo "✗ deploy env not found: $DEPLOY_ENV" >&2; exit 1; }
command -v stellar >/dev/null || { echo "✗ stellar CLI required (brew install stellar-cli)" >&2; exit 1; }

# Read a KEY=value (public address) from the deploy env. Never aborts (set -e
# safe): returns empty on no-match so the explicit require() can report it.
# Strips one surrounding quote pair and trims whitespace — no `xargs` (which would
# mangle values containing quotes/backslashes).
get() {
  local v
  v=$(grep -E "^$1=" "$DEPLOY_ENV" | head -1 | cut -d= -f2- || true)
  v="${v%\"}"; v="${v#\"}"
  v="${v#"${v%%[![:space:]]*}"}"   # ltrim
  v="${v%"${v##*[![:space:]]}"}"   # rtrim
  printf '%s' "$v"
}

# Invoke a read-only contract method; empty + non-fatal on failure (set -e safe).
invoke() { stellar contract invoke --network "$NET" --source-account "$SRC" --id "$1" -- "$2" 2>/dev/null | tr -d '"' || true; }

die() { echo "✗ $*" >&2; exit 1; }

# Read + validate one reserve's contract set. Sets <PFX>_{VAULT,POLICY,REGISTRY,
# SAC,FAUCET,CODE,ISSUER}. Validates the vault is live and its underlying matches
# the configured SAC (catches a stale/wrong id), then resolves the asset's
# CODE:ISSUER from the SAC's on-chain name().
load_reserve() {
  local pfx="$1" k val sac_name ua
  for k in VAULT POLICY REGISTRY SAC FAUCET; do
    val="$(get "${pfx}_${k}")"
    [ -n "$val" ] || die "missing ${pfx}_${k} in $DEPLOY_ENV"
    eval "${pfx}_${k}=\$val"
  done
  local vname="${pfx}_VAULT" sname="${pfx}_SAC"
  local vault="${!vname}" sac="${!sname}"
  # Vault must be live AND settle in the configured SAC — else the deploy env is stale.
  ua="$(invoke "$vault" query_asset)"
  [ -n "$ua" ] || die "${pfx}_VAULT $vault is not reachable on $NET (dead id, missing '$SRC' identity, or RPC down)"
  [ "$ua" = "$sac" ] || die "${pfx}_VAULT $vault underlying ($ua) != ${pfx}_SAC $sac — stale/wrong deploy env"
  # Asset code:issuer from the SAC's on-chain name() — the source of truth.
  sac_name="$(invoke "$sac" name)"
  [ -n "$sac_name" ] || die "could not read name() of ${pfx}_SAC $sac on $NET"
  case "$sac_name" in
    *:*) : ;;
    *)   die "${pfx}_SAC $sac name() = '$sac_name' is not CODE:ISSUER" ;;
  esac
  eval "${pfx}_CODE=\${sac_name%%:*}; ${pfx}_ISSUER=\${sac_name##*:}"
}

echo "→ reading $DEPLOY_ENV + validating reserves on-chain ($NET)…"
load_reserve MUSD
load_reserve MTESOURO
load_reserve MBRL
echo "  MUSD: $MUSD_CODE / $MUSD_ISSUER"
echo "  MTESOURO: $MTESOURO_CODE / $MTESOURO_ISSUER"
echo "  MBRL: $MBRL_CODE / $MBRL_ISSUER"

# ── Generate frontend/.env.example ────────────────────────────────────────────
cat > "$ROOT/frontend/.env.example" <<EOF
# Mutav Pulse — frontend env. Pre-filled with the LIVE testnet deploy, so a fresh
# clone just needs \`cp .env.example .env.local\`. All values are public testnet
# contract/asset IDs (no secrets). Three reserves live: MUSD · MTESOURO · MBRL.
#
# GENERATED by scripts/sync-deploy.sh — do not edit by hand; re-run
# \`make sync-deploy\` after a redeploy.

# ── Stellar network (testnet) ──
NEXT_PUBLIC_RPC_URL=$RPC_URL
NEXT_PUBLIC_NETWORK_PASSPHRASE=$NETWORK_PASSPHRASE
NEXT_PUBLIC_EXPLORER_BASE=$EXPLORER_BASE

# ── MUSD reserve (USD · $MUSD_CODE) — the primary reserve ──
NEXT_PUBLIC_VAULT_ID=$MUSD_VAULT
NEXT_PUBLIC_POLICY_ID=$MUSD_POLICY
NEXT_PUBLIC_REGISTRY_ID=$MUSD_REGISTRY
NEXT_PUBLIC_USDC_ID=$MUSD_SAC
NEXT_PUBLIC_USDC_CODE=$MUSD_CODE
NEXT_PUBLIC_USDC_ISSUER=$MUSD_ISSUER
NEXT_PUBLIC_FAUCET_ID=$MUSD_FAUCET

# ── MTESOURO reserve (Brazilian treasury · $MTESOURO_CODE) ──
NEXT_PUBLIC_MTESOURO_VAULT_ID=$MTESOURO_VAULT
NEXT_PUBLIC_MTESOURO_POLICY_ID=$MTESOURO_POLICY
NEXT_PUBLIC_MTESOURO_REGISTRY_ID=$MTESOURO_REGISTRY
NEXT_PUBLIC_TESOURO_CODE=$MTESOURO_CODE
NEXT_PUBLIC_TESOURO_ISSUER=$MTESOURO_ISSUER
NEXT_PUBLIC_TESOURO_PRICE_BRL=$TESOURO_PRICE_BRL
NEXT_PUBLIC_TESOURO_FAUCET_ID=$MTESOURO_FAUCET

# ── MBRL reserve (BRL-native · $MBRL_CODE) ──
NEXT_PUBLIC_MBRL_VAULT_ID=$MBRL_VAULT
NEXT_PUBLIC_MBRL_POLICY_ID=$MBRL_POLICY
NEXT_PUBLIC_MBRL_REGISTRY_ID=$MBRL_REGISTRY
NEXT_PUBLIC_CBRL_CODE=$MBRL_CODE
NEXT_PUBLIC_CBRL_ISSUER=$MBRL_ISSUER
NEXT_PUBLIC_CBRL_FAUCET_ID=$MBRL_FAUCET
EOF

# ── Generate docs/reference/deployments.md ────────────────────────────────────
row() { printf '| %s | [`%s`](%s/contract/%s) | %s |\n' "$1" "$2" "$EXPLORER_BASE" "$2" "$3"; }
{
cat <<EOF
# Testnet deployments

Live contract addresses and network configuration for the mutav-pulse reserves on
Stellar testnet. **Three reserves are live** — MUSD, MTESOURO, MBRL. These are
testnet artifacts; a redeploy (\`bootstrap.sh\`) issues new contract IDs. The
frontend reads every address from a \`NEXT_PUBLIC_*\` env var — it never hardcodes
them (see [\`../../frontend/.env.example\`](../../frontend/.env.example)).

> Generated by \`scripts/sync-deploy.sh\` — re-run \`make sync-deploy\` after a redeploy.

## Network

| Field | Value |
|---|---|
| Network | Stellar testnet |
| RPC URL | \`$RPC_URL\` |
| Network passphrase | \`$NETWORK_PASSPHRASE\` |
| Explorer | \`$EXPLORER_BASE\` |

## Reserves

Each reserve is its own contract set (vault + policy + registry), pegged to a
currency and settling in its own deposit token. Click an address to verify on
Stellar Expert.

### MUSD — USD reserve (deposit token: $MUSD_CODE)

| Contract | Address | Env var |
|---|---|---|
$(row vault "$MUSD_VAULT" '`NEXT_PUBLIC_VAULT_ID`')
$(row policy "$MUSD_POLICY" '`NEXT_PUBLIC_POLICY_ID`')
$(row registry "$MUSD_REGISTRY" '`NEXT_PUBLIC_REGISTRY_ID`')
$(row "$MUSD_CODE SAC (underlying)" "$MUSD_SAC" '`NEXT_PUBLIC_USDC_ID`')
$(row faucet "$MUSD_FAUCET" '`NEXT_PUBLIC_FAUCET_ID`')

### MTESOURO — Brazilian-treasury reserve (deposit token: $MTESOURO_CODE)

| Contract | Address | Env var |
|---|---|---|
$(row vault "$MTESOURO_VAULT" '`NEXT_PUBLIC_MTESOURO_VAULT_ID`')
$(row policy "$MTESOURO_POLICY" '`NEXT_PUBLIC_MTESOURO_POLICY_ID`')
$(row registry "$MTESOURO_REGISTRY" '`NEXT_PUBLIC_MTESOURO_REGISTRY_ID`')
$(row "$MTESOURO_CODE SAC (underlying)" "$MTESOURO_SAC" '— (read on-chain)')
$(row faucet "$MTESOURO_FAUCET" '`NEXT_PUBLIC_TESOURO_FAUCET_ID`')

### MBRL — BRL-native reserve (deposit token: $MBRL_CODE)

| Contract | Address | Env var |
|---|---|---|
$(row vault "$MBRL_VAULT" '`NEXT_PUBLIC_MBRL_VAULT_ID`')
$(row policy "$MBRL_POLICY" '`NEXT_PUBLIC_MBRL_POLICY_ID`')
$(row registry "$MBRL_REGISTRY" '`NEXT_PUBLIC_MBRL_REGISTRY_ID`')
$(row "$MBRL_CODE SAC (underlying)" "$MBRL_SAC" '— (read on-chain)')
$(row faucet "$MBRL_FAUCET" '`NEXT_PUBLIC_CBRL_FAUCET_ID`')

## Deposit assets

All three deposit tokens are **mock classic assets** on testnet. Each vault's
\`underlying\` is the asset's Stellar Asset Contract (SAC) above. The codes and
issuers below are read live from each SAC's on-chain \`name()\` — never copied by
hand (re-run \`make sync-deploy\` to refresh).

| Reserve | Deposit token | Issuer |
|---|---|---|
| MUSD | \`$MUSD_CODE\` | \`$MUSD_ISSUER\` |
| MTESOURO | \`$MTESOURO_CODE\` | \`$MTESOURO_ISSUER\` |
| MBRL | \`$MBRL_CODE\` | \`$MBRL_ISSUER\` |

## Notes

- All addresses are **testnet-only**; a redeploy via \`bootstrap.sh\` changes every
  contract ID. Re-run \`make sync-deploy\` to regenerate this file, \`.env.example\`,
  and the README block.
- The two-leg fiança policy is live: each reserve's \`policy\` exposes \`cover_default\`,
  \`cover_exit\`, \`grace_secs\`, and \`set_coverage_ratio_bps\`.
- For the per-method contract surface, see [\`./contracts/vault.md\`](./contracts/vault.md);
  for revert codes see [\`./errors.md\`](./errors.md).
EOF
} > "$ROOT/docs/reference/deployments.md"

# ── Regenerate the README "Live on testnet" block (between sentinels) ──────────
README="$ROOT/README.md"
if grep -q '<!-- deploy:start' "$README" && grep -q '<!-- deploy:end' "$README"; then
  blk="$(mktemp)"
  cat > "$blk" <<EOF
Primary reserve (MUSD) below; the full address set for all three reserves + their assets is in [\`docs/reference/deployments.md\`](docs/reference/deployments.md).

| Contract | Address | Verify |
|---|---|---|
| vault | \`$MUSD_VAULT\` | [stellar.expert]($EXPLORER_BASE/contract/$MUSD_VAULT) |
| policy | \`$MUSD_POLICY\` | [stellar.expert]($EXPLORER_BASE/contract/$MUSD_POLICY) |
| registry | \`$MUSD_REGISTRY\` | [stellar.expert]($EXPLORER_BASE/contract/$MUSD_REGISTRY) |

The MUSD vault settles in the $MUSD_CODE SAC \`$MUSD_SAC\`. The three deposit tokens ($MUSD_CODE / $MTESOURO_CODE / $MBRL_CODE) are mock testnet assets issued by \`$MUSD_ISSUER\`.
EOF
  awk -v blockfile="$blk" '
    index($0,"<!-- deploy:start")>0 { print; while ((getline l < blockfile) > 0) print l; close(blockfile); skip=1; next }
    index($0,"<!-- deploy:end")>0   { skip=0; print; next }
    !skip { print }
  ' "$README" > "$README.new" && mv "$README.new" "$README"
  rm -f "$blk"
  README_NOTE="    README.md (deploy block)"
else
  README_NOTE="    README.md — SKIPPED (no <!-- deploy:start/end --> sentinels found)"
fi

echo "✓ regenerated:"
echo "    frontend/.env.example"
echo "    docs/reference/deployments.md"
echo "$README_NOTE"
echo "  review with: git diff -- frontend/.env.example docs/reference/deployments.md README.md"
