#![no_std]
//! solvency_attestor — verifies the Groth16 (BN254) proof of the ZK solvency seal
//! on-chain and records the "green light". The verification key is embedded at
//! build time (see `build.rs`); the verification core is the lean version of
//! Nethermind's `circom-groth16-verifier` (same BN254 `pairing_check`).
//!
//! `attest` is PERMISSIONLESS (the proof is the authorization) and:
//!  - reads `guarantees_root` and `stable_assets` LIVE and uses them as public inputs → the
//!    proof only verifies if it was made for the current on-chain state (cross-check 4.2).
//!  - pins the bank-oracle pubkey in storage (admin) → closes the forgery of piece A.
//!  - requires freshness: `nonce` is the timestamp the oracle signed (window `WINDOW_SECS`).

extern crate alloc;

use soroban_sdk::{
    contract, contracterror, contractimpl, contracttype, symbol_short, vec, Address, Bytes, BytesN,
    Env, Vec, U256,
    crypto::bn254::{Bn254Fr, Bn254G1Affine as G1Affine, Bn254G2Affine as G2Affine},
};
use interfaces::{RegistryClient, VaultClient};

// VK constants generated by build.rs from verification_key.json.
// NB: the VK and `solvency_final.zkey` (Stage 2) are a PAIR — regenerating the zkey
// (new trusted setup) without re-committing `verification_key.json` would make the attestor
// reject valid proofs. Keep them in sync (see Stage 7/README).
include!(concat!(env!("OUT_DIR"), "/vk.rs"));

/// Freshness window: the bank's attestation (nonce=timestamp) cannot be older
/// than this. 1 hour.
const WINDOW_SECS: u64 = 3600;

/// Minimum accepted coverage band. `solvent` is only recorded `true` if the proof is
/// for at least 100% (10_000 bps). Without this floor, `attest` would accept a valid
/// low-band proof (e.g. 50%) and record `solvent:true` anyway — the flag would only
/// mean "a proof exists for SOME band", not "covered". With the floor, `solvent:true`
/// carries on-chain meaning (≥ 100%).
const MIN_RATIO_BPS: u32 = 10_000;

// Instance storage TTL (~5s/ledger): if less than ~7 days remain, extends to
// ~31 days. Without this, the attestation + the wiring (registry/vault/oracle) would
// expire and the seal would "vanish" (last_attestation -> None; attest -> NotConfigured).
const TTL_THRESHOLD: u32 = 120_960; // ~7 days
const TTL_EXTEND_TO: u32 = 535_680; // ~31 days

// ---------------------------------------------------------------------------
// Groth16 (BN254) verifier — embedded VK.
// ---------------------------------------------------------------------------

/// Groth16 verification errors.
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum Groth16Error {
    InvalidProof = 0,
    MalformedPublicInputs = 1,
    MalformedProof = 2,
}

/// Groth16 proof = points A, B, C. B (G2) in Soroban order c1||c0.
#[derive(Clone)]
#[contracttype]
pub struct Groth16Proof {
    pub a: G1Affine,
    pub b: G2Affine,
    pub c: G1Affine,
}

const G1_SIZE: u32 = 64;
const G2_SIZE: u32 = 128;
/// A (G1) || B (G2) || C (G1) = 64 + 128 + 64.
const PROOF_SIZE: u32 = G1_SIZE + G2_SIZE + G1_SIZE;

impl TryFrom<Bytes> for Groth16Proof {
    type Error = Groth16Error;
    fn try_from(value: Bytes) -> Result<Self, Self::Error> {
        if value.len() != PROOF_SIZE {
            return Err(Groth16Error::MalformedProof);
        }
        let a = G1Affine::from_bytes(
            value.slice(0..G1_SIZE).try_into().map_err(|_| Groth16Error::MalformedProof)?,
        );
        let b = G2Affine::from_bytes(
            value.slice(G1_SIZE..G1_SIZE + G2_SIZE).try_into().map_err(|_| Groth16Error::MalformedProof)?,
        );
        let c = G1Affine::from_bytes(
            value.slice(G1_SIZE + G2_SIZE..).try_into().map_err(|_| Groth16Error::MalformedProof)?,
        );
        Ok(Self { a, b, c })
    }
}

struct VerificationKey {
    alpha: G1Affine,
    beta: G2Affine,
    gamma: G2Affine,
    delta: G2Affine,
    ic: Vec<G1Affine>,
}

fn embedded_vk(env: &Env) -> VerificationKey {
    let mut ic: Vec<G1Affine> = Vec::new(env);
    for bytes in VK_IC.iter() {
        ic.push_back(G1Affine::from_bytes(BytesN::from_array(env, bytes)));
    }
    VerificationKey {
        alpha: G1Affine::from_bytes(BytesN::from_array(env, &VK_ALPHA_G1)),
        beta: G2Affine::from_bytes(BytesN::from_array(env, &VK_BETA_G2)),
        gamma: G2Affine::from_bytes(BytesN::from_array(env, &VK_GAMMA_G2)),
        delta: G2Affine::from_bytes(BytesN::from_array(env, &VK_DELTA_G2)),
        ic,
    }
}

/// Verifies `proof` against the embedded VK and the `public_inputs` (in circuit
/// order: guarantees_root, vault_stable_assets, ratio_bps, nonce, oracle_Ax, oracle_Ay).
/// `e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1`.
pub(crate) fn groth16_verify(
    env: &Env,
    proof: Groth16Proof,
    public_inputs: Vec<Bn254Fr>,
) -> Result<bool, Groth16Error> {
    let vk = embedded_vk(env);
    let bn = env.crypto().bn254();

    if public_inputs.len().checked_add(1) != Some(vk.ic.len()) {
        return Err(Groth16Error::MalformedPublicInputs);
    }

    let mut vk_x = vk.ic.get(0).ok_or(Groth16Error::MalformedPublicInputs)?;
    for i in 0..public_inputs.len() {
        let s = public_inputs.get(i).ok_or(Groth16Error::MalformedPublicInputs)?;
        let v = vk.ic.get(i + 1).ok_or(Groth16Error::MalformedPublicInputs)?;
        let prod = bn.g1_mul(&v, &s);
        vk_x = bn.g1_add(&vk_x, &prod);
    }

    #[allow(clippy::arithmetic_side_effects)]
    let neg_a = -proof.a;
    let g1_points = vec![env, neg_a, vk.alpha.clone(), vk_x, proof.c];
    let g2_points = vec![env, proof.b, vk.beta.clone(), vk.gamma.clone(), vk.delta.clone()];

    if bn.pairing_check(g1_points, g2_points) {
        Ok(true)
    } else {
        Err(Groth16Error::InvalidProof)
    }
}

// ---------------------------------------------------------------------------
// Contract: attest / last_attestation + wiring.
// ---------------------------------------------------------------------------

/// Attestor errors.
#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord)]
#[repr(u32)]
pub enum AttestError {
    InvalidProof = 0,
    MalformedPublicInputs = 1,
    MalformedProof = 2,
    /// `now - nonce > WINDOW_SECS` — attestation too old.
    StaleProof = 3,
    /// `nonce > now` — attestation "from the future".
    ProofFromFuture = 4,
    /// registry/vault/oracle have not been set yet.
    NotConfigured = 5,
    /// `ratio_bps < MIN_RATIO_BPS` — band below the coverage floor (100%).
    RatioTooLow = 6,
}

impl From<Groth16Error> for AttestError {
    fn from(e: Groth16Error) -> Self {
        match e {
            Groth16Error::InvalidProof => AttestError::InvalidProof,
            Groth16Error::MalformedPublicInputs => AttestError::MalformedPublicInputs,
            Groth16Error::MalformedProof => AttestError::MalformedProof,
        }
    }
}

/// The "green light" recorded on-chain. `solvent` is always true when recorded (an
/// invalid proof reverts); the front reads freshness via `ledger`/`ts`.
#[contracttype]
#[derive(Clone)]
pub struct Attestation {
    pub solvent: bool,
    pub ratio_bps: u32,
    pub ledger: u32,
    pub ts: u64,
}

#[contracttype]
enum DataKey {
    Admin,
    Registry,
    Vault,
    OracleAx,
    OracleAy,
    Last,
}

#[contract]
pub struct SolvencyAttestor;

#[contractimpl]
impl SolvencyAttestor {
    pub fn __constructor(e: &Env, admin: Address) {
        e.storage().instance().set(&DataKey::Admin, &admin);
    }

    pub fn admin(e: &Env) -> Address {
        e.storage().instance().get(&DataKey::Admin).unwrap()
    }

    fn require_admin(e: &Env) {
        let admin: Address = e.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();
    }

    fn bump_ttl(e: &Env) {
        e.storage().instance().extend_ttl(TTL_THRESHOLD, TTL_EXTEND_TO);
    }

    pub fn set_admin(e: Env, new_admin: Address) {
        Self::require_admin(&e);
        e.storage().instance().set(&DataKey::Admin, &new_admin);
    }

    pub fn set_registry(e: Env, addr: Address) {
        Self::require_admin(&e);
        e.storage().instance().set(&DataKey::Registry, &addr);
        Self::bump_ttl(&e);
    }

    pub fn set_vault(e: Env, addr: Address) {
        Self::require_admin(&e);
        e.storage().instance().set(&DataKey::Vault, &addr);
        Self::bump_ttl(&e);
    }

    /// Pins the bank-oracle's EdDSA pubkey (Ax/Ay coords as BE field elements).
    /// Without this, piece A would be forgeable (any prover would sign with their own key).
    pub fn set_oracle(e: Env, ax: BytesN<32>, ay: BytesN<32>) {
        Self::require_admin(&e);
        e.storage().instance().set(&DataKey::OracleAx, &ax);
        e.storage().instance().set(&DataKey::OracleAy, &ay);
        Self::bump_ttl(&e);
    }

    pub fn upgrade(e: Env, new_wasm_hash: BytesN<32>) {
        Self::require_admin(&e);
        e.deployer().update_current_contract_wasm(new_wasm_hash);
    }

    /// Verifies the proof against the live on-chain state and records the attestation.
    /// Public inputs reconstructed from the real state: a proof made for another state does not verify.
    /// `nonce` = timestamp signed by the oracle (freshness). PERMISSIONLESS.
    pub fn attest(e: Env, proof: Bytes, ratio_bps: u32, nonce: u64) -> Result<(), AttestError> {
        // Coverage floor: only attests `solvent` for band >= 100%. Ensures that
        // `solvent:true` means "covered" and not "proof of some arbitrary band".
        if ratio_bps < MIN_RATIO_BPS {
            return Err(AttestError::RatioTooLow);
        }

        let registry: Address =
            e.storage().instance().get(&DataKey::Registry).ok_or(AttestError::NotConfigured)?;
        let vault: Address =
            e.storage().instance().get(&DataKey::Vault).ok_or(AttestError::NotConfigured)?;
        let oracle_ax: BytesN<32> =
            e.storage().instance().get(&DataKey::OracleAx).ok_or(AttestError::NotConfigured)?;
        let oracle_ay: BytesN<32> =
            e.storage().instance().get(&DataKey::OracleAy).ok_or(AttestError::NotConfigured)?;

        // Freshness: nonce is the timestamp the bank-oracle signed.
        let now = e.ledger().timestamp();
        if nonce > now {
            return Err(AttestError::ProofFromFuture);
        }
        if now - nonce > WINDOW_SECS {
            return Err(AttestError::StaleProof);
        }

        // LIVE values (implicit cross-check 4.2).
        let root: BytesN<32> = RegistryClient::new(&e, &registry).guarantees_root();
        let stable: i128 = VaultClient::new(&e, &vault).stable_assets();
        let stable_u: u128 = if stable < 0 { 0 } else { stable as u128 };

        let proof = Groth16Proof::try_from(proof).map_err(AttestError::from)?;

        // Public inputs in circuit order.
        let mut pubs: Vec<Bn254Fr> = Vec::new(&e);
        pubs.push_back(Bn254Fr::from_bytes(root));
        pubs.push_back(Bn254Fr::from_u256(U256::from_u128(&e, stable_u)));
        pubs.push_back(Bn254Fr::from_u256(U256::from_u32(&e, ratio_bps)));
        pubs.push_back(Bn254Fr::from_u256(U256::from_u128(&e, nonce as u128)));
        pubs.push_back(Bn254Fr::from_bytes(oracle_ax));
        pubs.push_back(Bn254Fr::from_bytes(oracle_ay));

        groth16_verify(&e, proof, pubs).map_err(AttestError::from)?;

        let att = Attestation {
            solvent: true,
            ratio_bps,
            ledger: e.ledger().sequence(),
            ts: now,
        };
        e.storage().instance().set(&DataKey::Last, &att);
        Self::bump_ttl(&e);
        // Event so the front can react without polling.
        e.events().publish((symbol_short!("attested"),), att);
        Ok(())
    }

    /// Last recorded attestation (None if there never was one). Public read for the front.
    pub fn last_attestation(e: Env) -> Option<Attestation> {
        e.storage().instance().get(&DataKey::Last)
    }
}

#[cfg(test)]
mod test_fixture;
#[cfg(test)]
mod test;
